version: "3"
vars:
  OUTFILE: flatfile.tex.flat
tasks:
  flat-file:
    cmds:
      - |
        for f in $(find . -name '*.tex' -o -name '*.sty' -o -name '*.cls'); do
        echo "===== FILE: $f =====" | tee -a {{ .OUTFILE }}
        cat "$f" | tee -a {{ .OUTFILE }}
        done